task:
  name: "Firmware Dump by DumprX"
  only_if: $CIRRUS_REPO_OWNER == 'sungsong85'
  
  
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch

      privileged: true
      cpu: 4
      memory: 16G


  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - git clone https://gitlab.com/android-dump/qti/holi.git holi
      - cd holi 
      - cd dummy-device-tree 
      - cd oneplus 
      - cd CPH2381
      - ls
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

 
  Setup_script:
      - git config --global user.name "sungsong85"
      - git config --global user.email "sungsong85@gmail.com"
      
  
  Set-SSH-Keys_script:
      - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ''
      - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      
      
      - chmod 600 ~/.ssh/id_rsa
      - cd ~/.ssh 
      - cat id_rsa.pub
      
      
   Upload-scrpt:

     
      - cd holi 
      - cd dummy-device-tree 
      - cd oneplus 
      - cd CPH2381
      - git init 
      - git add .
      - git commit -m "first commit"
      - git branch -M main 
      - git remote add origin git@github.com:sungsong85/lineage_CPH2381.git
      - git push -u origin main 


